import type {
  Attraction,
  FoodPreference,
  Hotel,
  InterestCategory,
  MockTransportRecord,
  Restaurant,
} from "./domain";
import { CITY_COORDINATES, createLocation, type SupportedCity } from "./utils";

const COORD_OFFSETS = [
  [0.018, 0.012],
  [-0.022, 0.019],
  [0.014, -0.026],
  [-0.017, -0.021],
  [0.029, 0.004],
  [-0.011, 0.032],
] as const;

function withOffset(city: SupportedCity, index: number) {
  const base = CITY_COORDINATES[city];
  const offset = COORD_OFFSETS[index % COORD_OFFSETS.length] ?? [0, 0];
  return {
    latitude: Number((base.latitude + offset[0]).toFixed(5)),
    longitude: Number((base.longitude + offset[1]).toFixed(5)),
  };
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

export const mockFlights: MockTransportRecord[] = [
  {
    id: "flt-pat-goi-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Patna", "PAT", "Jay Prakash Narayan International Airport"),
    destination: createLocation("Goa", "GOI", "Manohar International Airport Goa"),
    departureClock: "08:30",
    durationMinutes: 165,
    price: 7200,
    currency: "INR",
    stops: 0,
    operator: "Mock Airways",
    serviceNumber: "MA-201",
    vehicleType: "Airbus A320",
    amenities: ["Cabin baggage", "Snack box"],
  },
  {
    id: "flt-pat-goi-2",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Patna", "PAT", "Jay Prakash Narayan International Airport"),
    destination: createLocation("Goa", "GOI", "Manohar International Airport Goa"),
    departureClock: "18:10",
    durationMinutes: 175,
    price: 8400,
    currency: "INR",
    stops: 0,
    operator: "Indigo Mock",
    serviceNumber: "IM-674",
    vehicleType: "Airbus A321",
  },
  {
    id: "flt-pat-del-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Patna", "PAT", "Jay Prakash Narayan International Airport"),
    destination: createLocation("Delhi", "DEL", "Indira Gandhi International Airport"),
    departureClock: "06:35",
    durationMinutes: 105,
    price: 4100,
    currency: "INR",
    stops: 0,
    operator: "Sky India Mock",
    serviceNumber: "SI-114",
    vehicleType: "Airbus A320",
  },
  {
    id: "flt-pat-del-2",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Patna", "PAT", "Jay Prakash Narayan International Airport"),
    destination: createLocation("Delhi", "DEL", "Indira Gandhi International Airport"),
    departureClock: "13:10",
    durationMinutes: 110,
    price: 4800,
    currency: "INR",
    stops: 0,
    operator: "Mock Airways",
    serviceNumber: "MA-117",
    vehicleType: "Boeing 737",
  },
  {
    id: "flt-del-goi-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Delhi", "DEL", "Indira Gandhi International Airport"),
    destination: createLocation("Goa", "GOI", "Manohar International Airport Goa"),
    departureClock: "11:45",
    durationMinutes: 165,
    price: 4300,
    currency: "INR",
    stops: 0,
    operator: "Coastal Wings Mock",
    serviceNumber: "CW-304",
    vehicleType: "Airbus A320neo",
  },
  {
    id: "flt-del-goi-2",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Delhi", "DEL", "Indira Gandhi International Airport"),
    destination: createLocation("Goa", "GOI", "Manohar International Airport Goa"),
    departureClock: "19:20",
    durationMinutes: 160,
    price: 5200,
    currency: "INR",
    stops: 0,
    operator: "Indigo Mock",
    serviceNumber: "IM-521",
    vehicleType: "Airbus A320",
  },
  {
    id: "flt-pat-bom-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Patna", "PAT", "Jay Prakash Narayan International Airport"),
    destination: createLocation("Mumbai", "BOM", "Chhatrapati Shivaji Maharaj International Airport"),
    departureClock: "07:50",
    durationMinutes: 145,
    price: 5300,
    currency: "INR",
    stops: 0,
    operator: "Mock Airways",
    serviceNumber: "MA-441",
    vehicleType: "Airbus A320",
  },
  {
    id: "flt-bom-goi-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Mumbai", "BOM", "Chhatrapati Shivaji Maharaj International Airport"),
    destination: createLocation("Goa", "GOI", "Manohar International Airport Goa"),
    departureClock: "13:05",
    durationMinutes: 75,
    price: 2500,
    currency: "INR",
    stops: 0,
    operator: "Coastal Wings Mock",
    serviceNumber: "CW-118",
    vehicleType: "ATR 72",
  },
  {
    id: "flt-bom-goi-2",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Mumbai", "BOM", "Chhatrapati Shivaji Maharaj International Airport"),
    destination: createLocation("Goa", "GOI", "Manohar International Airport Goa"),
    departureClock: "20:15",
    durationMinutes: 70,
    price: 3100,
    currency: "INR",
    stops: 0,
    operator: "Indigo Mock",
    serviceNumber: "IM-204",
    vehicleType: "Airbus A320",
  },
  {
    id: "flt-blr-goi-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Bengaluru", "BLR", "Kempegowda International Airport"),
    destination: createLocation("Goa", "GOI", "Manohar International Airport Goa"),
    departureClock: "09:40",
    durationMinutes: 80,
    price: 2800,
    currency: "INR",
    stops: 0,
    operator: "SouthLine Mock",
    serviceNumber: "SL-221",
    vehicleType: "Airbus A320",
  },
  {
    id: "flt-blr-goi-2",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Bengaluru", "BLR", "Kempegowda International Airport"),
    destination: createLocation("Goa", "GOI", "Manohar International Airport Goa"),
    departureClock: "17:55",
    durationMinutes: 85,
    price: 3300,
    currency: "INR",
    stops: 0,
    operator: "Mock Airways",
    serviceNumber: "MA-884",
  },
  {
    id: "flt-ccu-goi-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Kolkata", "CCU", "Netaji Subhas Chandra Bose International Airport"),
    destination: createLocation("Goa", "GOI", "Manohar International Airport Goa"),
    departureClock: "06:20",
    durationMinutes: 190,
    price: 6100,
    currency: "INR",
    stops: 0,
    operator: "East Coast Mock",
    serviceNumber: "EC-909",
  },
  {
    id: "flt-del-bom-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Delhi", "DEL", "Indira Gandhi International Airport"),
    destination: createLocation("Mumbai", "BOM", "Chhatrapati Shivaji Maharaj International Airport"),
    departureClock: "08:20",
    durationMinutes: 130,
    price: 4300,
    currency: "INR",
    stops: 0,
    operator: "Sky India Mock",
    serviceNumber: "SI-501",
  },
  {
    id: "flt-del-bom-2",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Delhi", "DEL", "Indira Gandhi International Airport"),
    destination: createLocation("Mumbai", "BOM", "Chhatrapati Shivaji Maharaj International Airport"),
    departureClock: "15:15",
    durationMinutes: 135,
    price: 3900,
    currency: "INR",
    stops: 0,
    operator: "Mock Airways",
    serviceNumber: "MA-717",
  },
  {
    id: "flt-del-blr-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Delhi", "DEL", "Indira Gandhi International Airport"),
    destination: createLocation("Bengaluru", "BLR", "Kempegowda International Airport"),
    departureClock: "07:00",
    durationMinutes: 170,
    price: 5600,
    currency: "INR",
    stops: 0,
    operator: "SouthLine Mock",
    serviceNumber: "SL-702",
  },
  {
    id: "flt-blr-bom-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Bengaluru", "BLR", "Kempegowda International Airport"),
    destination: createLocation("Mumbai", "BOM", "Chhatrapati Shivaji Maharaj International Airport"),
    departureClock: "12:40",
    durationMinutes: 105,
    price: 3400,
    currency: "INR",
    stops: 0,
    operator: "SouthLine Mock",
    serviceNumber: "SL-448",
  },
  {
    id: "flt-pat-ccu-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Patna", "PAT", "Jay Prakash Narayan International Airport"),
    destination: createLocation("Kolkata", "CCU", "Netaji Subhas Chandra Bose International Airport"),
    departureClock: "10:25",
    durationMinutes: 70,
    price: 3200,
    currency: "INR",
    stops: 0,
    operator: "East Coast Mock",
    serviceNumber: "EC-122",
  },
  {
    id: "flt-ccu-del-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Kolkata", "CCU", "Netaji Subhas Chandra Bose International Airport"),
    destination: createLocation("Delhi", "DEL", "Indira Gandhi International Airport"),
    departureClock: "14:10",
    durationMinutes: 145,
    price: 4700,
    currency: "INR",
    stops: 0,
    operator: "Sky India Mock",
    serviceNumber: "SI-316",
  },
  {
    id: "flt-jaipur-goi-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Jaipur", "JAI", "Jaipur International Airport"),
    destination: createLocation("Goa", "GOI", "Manohar International Airport Goa"),
    departureClock: "16:30",
    durationMinutes: 145,
    price: 4900,
    currency: "INR",
    stops: 0,
    operator: "Heritage Air Mock",
    serviceNumber: "HA-404",
  },
  {
    id: "flt-pat-jai-1",
    provider: "MOCK_FLIGHTS",
    mode: "FLIGHT",
    origin: createLocation("Patna", "PAT", "Jay Prakash Narayan International Airport"),
    destination: createLocation("Jaipur", "JAI", "Jaipur International Airport"),
    departureClock: "05:55",
    durationMinutes: 120,
    price: 4200,
    currency: "INR",
    stops: 0,
    operator: "Heritage Air Mock",
    serviceNumber: "HA-215",
  },
];

export const mockTrains: MockTransportRecord[] = [
  {
    id: "trn-pnbe-bct-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Patna", "PNBE", "Patna Junction"),
    destination: createLocation("Mumbai", "BCT", "Mumbai Central"),
    departureClock: "21:30",
    durationMinutes: 1_680,
    price: 2400,
    currency: "INR",
    stops: 18,
    operator: "Indian Railways Mock",
    serviceNumber: "12345",
    vehicleType: "Superfast Express",
    metadata: { trainName: "Patna Mumbai Superfast", classes: ["SL", "3A", "2A"] },
  },
  {
    id: "trn-pnbe-ndls-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Patna", "PNBE", "Patna Junction"),
    destination: createLocation("Delhi", "NDLS", "New Delhi Railway Station"),
    departureClock: "17:10",
    durationMinutes: 790,
    price: 1450,
    currency: "INR",
    stops: 9,
    operator: "Indian Railways Mock",
    serviceNumber: "12309",
    vehicleType: "Rajdhani-style Express",
    metadata: { trainName: "Bihar Delhi Express", classes: ["3A", "2A", "1A"] },
  },
  {
    id: "trn-ndls-mao-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Delhi", "NDLS", "New Delhi Railway Station"),
    destination: createLocation("Goa", "MAO", "Madgaon Junction"),
    departureClock: "15:00",
    durationMinutes: 1_950,
    price: 2850,
    currency: "INR",
    stops: 22,
    operator: "Indian Railways Mock",
    serviceNumber: "22414",
    vehicleType: "Express",
    metadata: { trainName: "Goa Sampark Mock", classes: ["SL", "3A", "2A"] },
  },
  {
    id: "trn-bct-mao-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Mumbai", "BCT", "Mumbai Central"),
    destination: createLocation("Goa", "MAO", "Madgaon Junction"),
    departureClock: "06:00",
    durationMinutes: 610,
    price: 950,
    currency: "INR",
    stops: 11,
    operator: "Indian Railways Mock",
    serviceNumber: "10111",
    vehicleType: "Konkan Express",
    metadata: { trainName: "Konkan Coast Express", classes: ["CC", "2S", "SL"] },
  },
  {
    id: "trn-bct-mao-2",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Mumbai", "BCT", "Mumbai Central"),
    destination: createLocation("Goa", "MAO", "Madgaon Junction"),
    departureClock: "23:40",
    durationMinutes: 525,
    price: 1250,
    currency: "INR",
    stops: 8,
    operator: "Indian Railways Mock",
    serviceNumber: "22119",
    vehicleType: "Overnight Superfast",
    metadata: { trainName: "Mumbai Goa Night Express", classes: ["SL", "3A"] },
  },
  {
    id: "trn-sbc-mao-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Bengaluru", "SBC", "KSR Bengaluru"),
    destination: createLocation("Goa", "MAO", "Madgaon Junction"),
    departureClock: "20:15",
    durationMinutes: 720,
    price: 1150,
    currency: "INR",
    stops: 10,
    operator: "Indian Railways Mock",
    serviceNumber: "17309",
    vehicleType: "Overnight Express",
    metadata: { trainName: "Bengaluru Vasco Express", classes: ["SL", "3A", "2A"] },
  },
  {
    id: "trn-hwh-mao-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Kolkata", "HWH", "Howrah Junction"),
    destination: createLocation("Goa", "MAO", "Madgaon Junction"),
    departureClock: "23:20",
    durationMinutes: 2_280,
    price: 3100,
    currency: "INR",
    stops: 27,
    operator: "Indian Railways Mock",
    serviceNumber: "18047",
    vehicleType: "Weekly Express",
    metadata: { trainName: "Amaravati Coast Mock", classes: ["SL", "3A"] },
  },
  {
    id: "trn-pnbe-bsb-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Patna", "PNBE", "Patna Junction"),
    destination: createLocation("Varanasi", "BSB", "Varanasi Junction"),
    departureClock: "05:40",
    durationMinutes: 235,
    price: 420,
    currency: "INR",
    stops: 5,
    operator: "Indian Railways Mock",
    serviceNumber: "13257",
    vehicleType: "Intercity Express",
    metadata: { trainName: "Kashi Intercity Mock", classes: ["2S", "CC"] },
  },
  {
    id: "trn-bsb-mao-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Varanasi", "BSB", "Varanasi Junction"),
    destination: createLocation("Goa", "MAO", "Madgaon Junction"),
    departureClock: "13:30",
    durationMinutes: 1_980,
    price: 2650,
    currency: "INR",
    stops: 24,
    operator: "Indian Railways Mock",
    serviceNumber: "12742",
    vehicleType: "Express",
    metadata: { trainName: "Kashi Konkan Express", classes: ["SL", "3A", "2A"] },
  },
  {
    id: "trn-ndls-bct-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Delhi", "NDLS", "New Delhi Railway Station"),
    destination: createLocation("Mumbai", "BCT", "Mumbai Central"),
    departureClock: "16:55",
    durationMinutes: 960,
    price: 2050,
    currency: "INR",
    stops: 8,
    operator: "Indian Railways Mock",
    serviceNumber: "12952",
    vehicleType: "Rajdhani-style Express",
    metadata: { trainName: "Mumbai Rajdhani Mock", classes: ["3A", "2A", "1A"] },
  },
  {
    id: "trn-ndls-jp-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Delhi", "NDLS", "New Delhi Railway Station"),
    destination: createLocation("Jaipur", "JP", "Jaipur Junction"),
    departureClock: "06:05",
    durationMinutes: 275,
    price: 520,
    currency: "INR",
    stops: 5,
    operator: "Indian Railways Mock",
    serviceNumber: "12015",
    vehicleType: "Shatabdi-style Chair Car",
    metadata: { trainName: "Ajmer Shatabdi Mock", classes: ["CC", "EC"] },
  },
  {
    id: "trn-jp-mao-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Jaipur", "JP", "Jaipur Junction"),
    destination: createLocation("Goa", "MAO", "Madgaon Junction"),
    departureClock: "12:25",
    durationMinutes: 1_430,
    price: 2300,
    currency: "INR",
    stops: 19,
    operator: "Indian Railways Mock",
    serviceNumber: "12978",
    vehicleType: "Superfast Express",
    metadata: { trainName: "Rajasthan Konkan Express", classes: ["SL", "3A"] },
  },
  {
    id: "trn-pnbe-hwh-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Patna", "PNBE", "Patna Junction"),
    destination: createLocation("Kolkata", "HWH", "Howrah Junction"),
    departureClock: "06:55",
    durationMinutes: 500,
    price: 880,
    currency: "INR",
    stops: 7,
    operator: "Indian Railways Mock",
    serviceNumber: "12304",
    vehicleType: "Poorva-style Express",
    metadata: { trainName: "Patna Howrah Express", classes: ["SL", "3A", "2A"] },
  },
  {
    id: "trn-bct-sbc-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Mumbai", "BCT", "Mumbai Central"),
    destination: createLocation("Bengaluru", "SBC", "KSR Bengaluru"),
    departureClock: "08:10",
    durationMinutes: 1_150,
    price: 1750,
    currency: "INR",
    stops: 14,
    operator: "Indian Railways Mock",
    serviceNumber: "11301",
    vehicleType: "Udyan-style Express",
    metadata: { trainName: "Deccan Bengaluru Express", classes: ["SL", "3A"] },
  },
  {
    id: "trn-pnbe-jp-1",
    provider: "MOCK_TRAINS",
    mode: "TRAIN",
    origin: createLocation("Patna", "PNBE", "Patna Junction"),
    destination: createLocation("Jaipur", "JP", "Jaipur Junction"),
    departureClock: "19:35",
    durationMinutes: 1_025,
    price: 1650,
    currency: "INR",
    stops: 13,
    operator: "Indian Railways Mock",
    serviceNumber: "12948",
    vehicleType: "Express",
    metadata: { trainName: "Bihar Rajasthan Mock", classes: ["SL", "3A"] },
  },
];

export const mockBuses: MockTransportRecord[] = [
  {
    id: "bus-pat-bsb-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Patna", "PAT-BUS", "Mithapur Bus Stand"),
    destination: createLocation("Varanasi", "VNS-BUS", "Varanasi Cantt Bus Stand"),
    departureClock: "06:30",
    durationMinutes: 360,
    price: 650,
    currency: "INR",
    stops: 2,
    operator: "Ganga Volvo Mock",
    serviceNumber: "GV-31",
    vehicleType: "AC Seater",
    metadata: { boarding: ["Mithapur", "Patna Bypass"], dropping: ["Cantt", "Lahartara"] },
  },
  {
    id: "bus-pat-bsb-2",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Patna", "PAT-BUS", "Mithapur Bus Stand"),
    destination: createLocation("Varanasi", "VNS-BUS", "Varanasi Cantt Bus Stand"),
    departureClock: "22:00",
    durationMinutes: 390,
    price: 780,
    currency: "INR",
    stops: 1,
    operator: "Kashi Sleeper Mock",
    serviceNumber: "KS-88",
    vehicleType: "AC Sleeper",
    metadata: { boarding: ["Mithapur"], dropping: ["Cantt"] },
  },
  {
    id: "bus-bom-goi-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Mumbai", "BOM-BUS", "Mumbai Borivali Bus Terminal"),
    destination: createLocation("Goa", "GOA-BUS", "Mapusa Bus Stand"),
    departureClock: "21:15",
    durationMinutes: 675,
    price: 1250,
    currency: "INR",
    stops: 3,
    operator: "Konkan Travels Mock",
    serviceNumber: "KT-501",
    vehicleType: "AC Sleeper",
    metadata: { boarding: ["Borivali", "Sion", "Vashi"], dropping: ["Mapusa", "Panaji"] },
  },
  {
    id: "bus-bom-goi-2",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Mumbai", "BOM-BUS", "Mumbai Central Bus Depot"),
    destination: createLocation("Goa", "GOA-BUS", "Panaji Bus Stand"),
    departureClock: "18:45",
    durationMinutes: 720,
    price: 980,
    currency: "INR",
    stops: 4,
    operator: "Coastal Express Mock",
    serviceNumber: "CE-211",
    vehicleType: "Non-AC Sleeper",
  },
  {
    id: "bus-blr-goi-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Bengaluru", "BLR-BUS", "Majestic Bus Stand"),
    destination: createLocation("Goa", "GOA-BUS", "Panaji Bus Stand"),
    departureClock: "20:30",
    durationMinutes: 660,
    price: 1350,
    currency: "INR",
    stops: 3,
    operator: "Western Ghats Mock",
    serviceNumber: "WG-710",
    vehicleType: "AC Sleeper",
  },
  {
    id: "bus-blr-goi-2",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Bengaluru", "BLR-BUS", "Anand Rao Circle"),
    destination: createLocation("Goa", "GOA-BUS", "Mapusa Bus Stand"),
    departureClock: "22:20",
    durationMinutes: 690,
    price: 1180,
    currency: "INR",
    stops: 2,
    operator: "SeaLink Bus Mock",
    serviceNumber: "SB-441",
    vehicleType: "AC Semi Sleeper",
  },
  {
    id: "bus-del-jp-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Delhi", "DEL-BUS", "Kashmere Gate ISBT"),
    destination: createLocation("Jaipur", "JAI-BUS", "Sindhi Camp Bus Stand"),
    departureClock: "07:00",
    durationMinutes: 330,
    price: 620,
    currency: "INR",
    stops: 2,
    operator: "Rajasthan Road Mock",
    serviceNumber: "RR-102",
    vehicleType: "Volvo Seater",
  },
  {
    id: "bus-del-jp-2",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Delhi", "DEL-BUS", "Dhaula Kuan Pickup"),
    destination: createLocation("Jaipur", "JAI-BUS", "Sindhi Camp Bus Stand"),
    departureClock: "23:10",
    durationMinutes: 310,
    price: 740,
    currency: "INR",
    stops: 1,
    operator: "Pink City Volvo Mock",
    serviceNumber: "PC-77",
    vehicleType: "AC Sleeper",
  },
  {
    id: "bus-jp-bom-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Jaipur", "JAI-BUS", "Sindhi Camp Bus Stand"),
    destination: createLocation("Mumbai", "BOM-BUS", "Mumbai Central Bus Depot"),
    departureClock: "16:45",
    durationMinutes: 1_050,
    price: 1900,
    currency: "INR",
    stops: 6,
    operator: "Desert Konkan Mock",
    serviceNumber: "DK-505",
    vehicleType: "AC Sleeper",
  },
  {
    id: "bus-del-bom-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Delhi", "DEL-BUS", "Kashmere Gate ISBT"),
    destination: createLocation("Mumbai", "BOM-BUS", "Mumbai Central Bus Depot"),
    departureClock: "14:30",
    durationMinutes: 1_480,
    price: 2600,
    currency: "INR",
    stops: 8,
    operator: "North West Sleeper Mock",
    serviceNumber: "NW-901",
    vehicleType: "AC Sleeper",
  },
  {
    id: "bus-pat-del-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Patna", "PAT-BUS", "Mithapur Bus Stand"),
    destination: createLocation("Delhi", "DEL-BUS", "Kashmere Gate ISBT"),
    departureClock: "15:45",
    durationMinutes: 1_010,
    price: 2200,
    currency: "INR",
    stops: 7,
    operator: "Grand Trunk Mock",
    serviceNumber: "GT-220",
    vehicleType: "AC Sleeper",
  },
  {
    id: "bus-pat-kolkata-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Patna", "PAT-BUS", "Mithapur Bus Stand"),
    destination: createLocation("Kolkata", "CCU-BUS", "Esplanade Bus Stand"),
    departureClock: "19:00",
    durationMinutes: 720,
    price: 1200,
    currency: "INR",
    stops: 4,
    operator: "East Highway Mock",
    serviceNumber: "EH-84",
    vehicleType: "AC Sleeper",
  },
  {
    id: "bus-kolkata-bhub-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Kolkata", "CCU-BUS", "Esplanade Bus Stand"),
    destination: createLocation("Bengaluru", "BLR-BUS", "Majestic Bus Stand"),
    departureClock: "10:00",
    durationMinutes: 1_980,
    price: 3400,
    currency: "INR",
    stops: 10,
    operator: "East South Corridor Mock",
    serviceNumber: "ESC-16",
    vehicleType: "AC Sleeper",
  },
  {
    id: "bus-varanasi-delhi-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Varanasi", "VNS-BUS", "Varanasi Cantt Bus Stand"),
    destination: createLocation("Delhi", "DEL-BUS", "Kashmere Gate ISBT"),
    departureClock: "18:40",
    durationMinutes: 760,
    price: 1500,
    currency: "INR",
    stops: 5,
    operator: "Kashi Delhi Mock",
    serviceNumber: "KD-41",
    vehicleType: "AC Sleeper",
  },
  {
    id: "bus-varanasi-goa-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Varanasi", "VNS-BUS", "Varanasi Cantt Bus Stand"),
    destination: createLocation("Goa", "GOA-BUS", "Panaji Bus Stand"),
    departureClock: "09:15",
    durationMinutes: 2_040,
    price: 3600,
    currency: "INR",
    stops: 11,
    operator: "Pilgrim Coast Mock",
    serviceNumber: "PC-612",
    vehicleType: "AC Sleeper",
  },
  {
    id: "bus-jaipur-goa-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Jaipur", "JAI-BUS", "Sindhi Camp Bus Stand"),
    destination: createLocation("Goa", "GOA-BUS", "Panaji Bus Stand"),
    departureClock: "18:00",
    durationMinutes: 1_440,
    price: 2500,
    currency: "INR",
    stops: 7,
    operator: "Desert Sea Mock",
    serviceNumber: "DS-301",
    vehicleType: "AC Sleeper",
  },
  {
    id: "bus-mumbai-bengaluru-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Mumbai", "BOM-BUS", "Mumbai Central Bus Depot"),
    destination: createLocation("Bengaluru", "BLR-BUS", "Majestic Bus Stand"),
    departureClock: "17:30",
    durationMinutes: 1_030,
    price: 2100,
    currency: "INR",
    stops: 5,
    operator: "Deccan Sleeper Mock",
    serviceNumber: "DS-770",
    vehicleType: "AC Sleeper",
  },
  {
    id: "bus-del-goi-1",
    provider: "MOCK_BUSES",
    mode: "BUS",
    origin: createLocation("Delhi", "DEL-BUS", "Kashmere Gate ISBT"),
    destination: createLocation("Goa", "GOA-BUS", "Panaji Bus Stand"),
    departureClock: "12:15",
    durationMinutes: 1_860,
    price: 3300,
    currency: "INR",
    stops: 10,
    operator: "Capital Coast Mock",
    serviceNumber: "CC-993",
    vehicleType: "AC Sleeper",
  },
];

const hotelNames: Record<SupportedCity, string[]> = {
  Goa: ["Goa Beach Stay", "Panaji Garden Rooms", "Calangute Blue Inn", "Mandovi Comforts", "Coconut Grove Suites"],
  Delhi: ["Connaught Budget Inn", "Aerocity Transit Stay", "Karol Bagh Comfort", "Saket Urban Hotel", "Old Delhi Heritage Rooms"],
  Mumbai: ["Marine Drive Residency", "Bandra Urban Stay", "Dadar Comfort Hotel", "Colaba Port Inn", "Andheri Transit Suites"],
  Jaipur: ["Pink City Haveli", "Amber View Stay", "MI Road Comfort", "Bani Park Boutique", "Jal Mahal Retreat"],
  Varanasi: ["Ganga View Lodge", "Kashi Heritage Stay", "Assi Comfort Rooms", "Sarnath Garden Inn", "Dashashwamedh Guest House"],
  Bengaluru: ["Indiranagar Studio Stay", "MG Road Business Inn", "Koramangala Comfort", "Lalbagh Garden Hotel", "Whitefield Transit Suites"],
  Patna: ["Patna Junction Rooms", "Gandhi Maidan Stay", "Bailey Road Comfort", "Airport Budget Inn", "Ganga Riverside Hotel"],
  Kolkata: ["Park Street Comfort", "Howrah Transit Inn", "Salt Lake Suites", "Esplanade Heritage Stay", "Ballygunge Garden Hotel"],
};

export const mockHotels: Hotel[] = Object.entries(hotelNames).flatMap(([cityRaw, names]) => {
  const city = cityRaw as SupportedCity;
  return names.map((name, index) => {
    const coords = withOffset(city, index);
    const priceBase = city === "Goa" ? 2_000 : city === "Mumbai" ? 2_600 : 1_700;
    return {
      id: `hotel-${slug(city)}-${index + 1}`,
      type: "HOTEL",
      name,
      city,
      location: `${name.split(" ")[0]} district, ${city}`,
      ...coords,
      rating: Number((4.1 + (index % 5) * 0.12).toFixed(1)),
      reviewCount: 240 + index * 86,
      pricePerNight: priceBase + index * 450,
      priceLevel: index < 2 ? "BUDGET" : index < 4 ? "MID_RANGE" : "PREMIUM",
      estimatedCost: priceBase + index * 450,
      amenities: index % 2 === 0 ? ["WiFi", "Breakfast", "Airport pickup"] : ["WiFi", "Pool", "Laundry"],
      roomType: index % 3 === 0 ? "Deluxe double" : index % 3 === 1 ? "Standard queen" : "Family room",
      distanceFromCenterKm: Number((0.8 + index * 0.9).toFixed(1)),
      cancellationPolicy: index % 2 === 0 ? "Free cancellation up to 24 hours" : "Partial refund before check-in",
      source: "MOCK",
    } satisfies Hotel;
  });
});

const attractionsByCity: Record<SupportedCity, Array<[string, InterestCategory, number, number, string]>> = {
  Goa: [
    ["Baga Beach", "BEACH", 0, 180, "Morning or sunset"],
    ["Calangute Beach", "BEACH", 0, 150, "Morning"],
    ["Fort Aguada", "HISTORY", 25, 120, "Late afternoon"],
    ["Dudhsagar Falls", "NATURE", 500, 240, "Morning"],
    ["Basilica of Bom Jesus", "CULTURE", 0, 90, "Morning"],
    ["Anjuna Flea Market", "SHOPPING", 0, 120, "Evening"],
    ["Chapora Fort", "HISTORY", 0, 90, "Sunset"],
    ["Divar Island Trail", "NATURE", 250, 180, "Morning"],
    ["Goa State Museum", "MUSEUM", 50, 90, "Afternoon"],
  ],
  Delhi: [
    ["Red Fort", "HISTORY", 50, 150, "Morning"],
    ["Qutub Minar", "HISTORY", 40, 120, "Morning"],
    ["India Gate", "CULTURE", 0, 60, "Evening"],
    ["Lodhi Garden", "NATURE", 0, 90, "Morning"],
    ["National Museum", "MUSEUM", 20, 120, "Afternoon"],
    ["Lotus Temple", "RELIGIOUS", 0, 75, "Late afternoon"],
    ["Dilli Haat", "SHOPPING", 30, 120, "Evening"],
    ["Humayun's Tomb", "HISTORY", 40, 120, "Morning"],
  ],
  Mumbai: [
    ["Gateway of India", "HISTORY", 0, 75, "Morning"],
    ["Marine Drive", "NATURE", 0, 90, "Sunset"],
    ["Elephanta Caves", "HISTORY", 600, 210, "Morning"],
    ["Chhatrapati Shivaji Maharaj Vastu Sangrahalaya", "MUSEUM", 150, 150, "Afternoon"],
    ["Juhu Beach", "BEACH", 0, 120, "Evening"],
    ["Colaba Causeway", "SHOPPING", 0, 100, "Evening"],
    ["Sanjay Gandhi National Park", "NATURE", 85, 180, "Morning"],
    ["Bandra Fort", "HISTORY", 0, 75, "Sunset"],
  ],
  Jaipur: [
    ["Amber Fort", "HISTORY", 100, 180, "Morning"],
    ["Hawa Mahal", "CULTURE", 50, 75, "Morning"],
    ["City Palace", "HISTORY", 200, 150, "Afternoon"],
    ["Jantar Mantar", "MUSEUM", 50, 90, "Afternoon"],
    ["Nahargarh Fort", "HISTORY", 50, 120, "Sunset"],
    ["Johari Bazaar", "SHOPPING", 0, 120, "Evening"],
    ["Jal Mahal Viewpoint", "NATURE", 0, 60, "Morning"],
    ["Galta Ji Temple", "RELIGIOUS", 0, 90, "Morning"],
  ],
  Varanasi: [
    ["Dashashwamedh Ghat", "CULTURE", 0, 120, "Evening"],
    ["Kashi Vishwanath Temple", "RELIGIOUS", 0, 120, "Morning"],
    ["Sarnath", "HISTORY", 50, 180, "Morning"],
    ["Assi Ghat", "CULTURE", 0, 90, "Morning"],
    ["Ramnagar Fort", "HISTORY", 75, 120, "Afternoon"],
    ["Banaras Hindu University Campus", "CULTURE", 0, 90, "Afternoon"],
    ["Manikarnika Ghat Walk", "CULTURE", 0, 75, "Late afternoon"],
    ["Godowlia Market", "SHOPPING", 0, 120, "Evening"],
  ],
  Bengaluru: [
    ["Lalbagh Botanical Garden", "NATURE", 30, 120, "Morning"],
    ["Bangalore Palace", "HISTORY", 250, 120, "Afternoon"],
    ["Cubbon Park", "NATURE", 0, 90, "Morning"],
    ["Vidhana Soudha Viewpoint", "CULTURE", 0, 45, "Evening"],
    ["National Gallery of Modern Art", "MUSEUM", 50, 120, "Afternoon"],
    ["ISKCON Temple Bengaluru", "RELIGIOUS", 0, 90, "Evening"],
    ["Commercial Street", "SHOPPING", 0, 120, "Evening"],
    ["Nandi Hills Sunrise", "ADVENTURE", 300, 210, "Early morning"],
    ["Bannerghatta Biological Park", "NATURE", 120, 180, "Morning"],
  ],
  Patna: [
    ["Golghar", "HISTORY", 20, 60, "Morning"],
    ["Bihar Museum", "MUSEUM", 100, 120, "Afternoon"],
    ["Takht Sri Patna Sahib", "RELIGIOUS", 0, 90, "Morning"],
    ["Gandhi Maidan", "CULTURE", 0, 60, "Evening"],
    ["Eco Park Patna", "NATURE", 30, 90, "Morning"],
  ],
  Kolkata: [
    ["Victoria Memorial", "HISTORY", 50, 120, "Morning"],
    ["Indian Museum", "MUSEUM", 75, 150, "Afternoon"],
    ["Howrah Bridge Viewpoint", "CULTURE", 0, 60, "Evening"],
    ["Dakshineswar Kali Temple", "RELIGIOUS", 0, 90, "Morning"],
    ["New Market", "SHOPPING", 0, 120, "Evening"],
  ],
};

export const mockAttractions: Attraction[] = Object.entries(attractionsByCity).flatMap(
  ([cityRaw, attractions]) => {
    const city = cityRaw as SupportedCity;
    return attractions.map(([name, category, fee, duration, bestTime], index) => {
      const coords = withOffset(city, index);
      return {
        id: `attraction-${slug(city)}-${slug(name)}`,
        type: "ATTRACTION",
        name,
        city,
        location: `${name}, ${city}`,
        ...coords,
        rating: Number((4.2 + (index % 4) * 0.1).toFixed(1)),
        priceLevel: fee === 0 ? "BUDGET" : fee > 200 ? "MID_RANGE" : "BUDGET",
        estimatedCost: fee,
        category,
        entryFee: fee,
        openingHours: category === "BEACH" || category === "NATURE" ? "06:00-19:00" : "09:00-18:00",
        recommendedDurationMinutes: duration,
        bestTimeToVisit: bestTime,
        source: "MOCK",
      } satisfies Attraction;
    });
  },
);

const restaurantsByCity: Record<SupportedCity, Array<[string, string, number, boolean, boolean, FoodPreference[]]>> = {
  Goa: [
    ["Viva Panjim Mock Kitchen", "Goan", 650, true, false, ["LOCAL", "NON_VEGETARIAN"]],
    ["Plantain Beach Cafe", "Vegetarian coastal", 420, true, true, ["VEGETARIAN", "VEGAN", "LOCAL"]],
    ["Calangute Thali House", "Indian thali", 320, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Mandovi Grill Room", "Seafood", 900, false, false, ["NON_VEGETARIAN", "LOCAL"]],
    ["Anjuna Garden Bowls", "Cafe", 520, true, true, ["VEGETARIAN", "VEGAN"]],
  ],
  Delhi: [
    ["Karol Bagh Chole Corner", "North Indian", 280, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Connaught Tandoor Mock", "Mughlai", 720, true, false, ["NON_VEGETARIAN", "LOCAL"]],
    ["Saket Millet Cafe", "Healthy cafe", 580, true, true, ["VEGETARIAN", "VEGAN"]],
    ["Old Delhi Paratha House", "Street food", 240, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Aerocity Global Kitchen", "Multi-cuisine", 950, true, true, ["VEGETARIAN", "NON_VEGETARIAN"]],
  ],
  Mumbai: [
    ["Colaba Coastal Mock", "Seafood", 880, false, false, ["NON_VEGETARIAN", "LOCAL"]],
    ["Dadar Misal House", "Maharashtrian", 260, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Bandra Vegan Bowl", "Vegan cafe", 620, true, true, ["VEGETARIAN", "VEGAN"]],
    ["Juhu Pav Bhaji Stop", "Street food", 220, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Marine Drive Bistro", "Continental", 1_050, true, false, ["VEGETARIAN", "NON_VEGETARIAN"]],
  ],
  Jaipur: [
    ["Bani Park Dal Baati", "Rajasthani", 360, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Amber Rooftop Mock", "North Indian", 760, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Johari Bazaar Snacks", "Street food", 220, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Pink City Vegan Table", "Vegan", 560, true, true, ["VEGETARIAN", "VEGAN"]],
    ["MI Road Grill", "Multi-cuisine", 820, true, false, ["NON_VEGETARIAN", "VEGETARIAN"]],
  ],
  Varanasi: [
    ["Assi Ghat Kachori", "Street food", 180, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Kashi Satvik Bhoj", "Vegetarian thali", 300, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Ganga View Cafe", "Cafe", 480, true, true, ["VEGETARIAN", "VEGAN"]],
    ["Godowlia Lassi House", "Dessert", 160, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Sarnath Garden Kitchen", "North Indian", 520, true, false, ["VEGETARIAN"]],
  ],
  Bengaluru: [
    ["Indiranagar Dosa Bar", "South Indian", 280, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Koramangala Vegan Lab", "Vegan", 620, true, true, ["VEGETARIAN", "VEGAN"]],
    ["MG Road Grill Mock", "Multi-cuisine", 840, true, false, ["NON_VEGETARIAN", "VEGETARIAN"]],
    ["Lalbagh Filter Coffee House", "Cafe", 260, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Whitefield Bowl Kitchen", "Asian", 720, true, true, ["VEGETARIAN", "VEGAN"]],
  ],
  Patna: [
    ["Gandhi Maidan Litti House", "Bihari", 220, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Bailey Road Thali", "North Indian", 320, true, false, ["VEGETARIAN"]],
    ["Patna Grill Mock", "Multi-cuisine", 680, true, false, ["NON_VEGETARIAN", "VEGETARIAN"]],
    ["Airport Cafe Patna", "Cafe", 420, true, true, ["VEGETARIAN", "VEGAN"]],
    ["Kankarbagh Rolls", "Street food", 260, false, false, ["NON_VEGETARIAN", "LOCAL"]],
  ],
  Kolkata: [
    ["Park Street Roll House", "Bengali", 360, true, false, ["NON_VEGETARIAN", "LOCAL"]],
    ["Ballygunge Veg Table", "Vegetarian Bengali", 420, true, false, ["VEGETARIAN", "LOCAL"]],
    ["Salt Lake Vegan Cafe", "Vegan", 590, true, true, ["VEGETARIAN", "VEGAN"]],
    ["Esplanade Chow House", "Indo-Chinese", 520, true, false, ["NON_VEGETARIAN", "VEGETARIAN"]],
    ["Howrah Mishti Stop", "Dessert", 180, true, false, ["VEGETARIAN", "LOCAL"]],
  ],
};

export const mockRestaurants: Restaurant[] = Object.entries(restaurantsByCity).flatMap(
  ([cityRaw, restaurants]) => {
    const city = cityRaw as SupportedCity;
    return restaurants.map(([name, cuisine, cost, vegetarian, vegan, tags], index) => {
      const coords = withOffset(city, index + 2);
      return {
        id: `restaurant-${slug(city)}-${slug(name)}`,
        type: "RESTAURANT",
        name,
        city,
        location: `${name}, ${city}`,
        ...coords,
        rating: Number((4.0 + (index % 5) * 0.13).toFixed(1)),
        priceLevel: cost <= 350 ? "BUDGET" : cost <= 700 ? "MID_RANGE" : "PREMIUM",
        estimatedCost: cost,
        cuisine,
        vegetarianAvailable: vegetarian,
        veganAvailable: vegan,
        openingHours: "08:00-23:00",
        mealCostPerPerson: cost,
        tags,
        source: "MOCK",
      } satisfies Restaurant;
    });
  },
);
